<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="DESKTOP-MC9GRJJ" ignored="0" name="Test" tests="1" failures="1" timestamp="2020-12-30T01:44:14 IST" time="20.174" errors="0">
  <testcase name="TestCase2" time="3.63" classname="com.tricentis.sampleapp.Test.LoginTest2">
    <failure type="java.lang.AssertionError" message="expected [False] but found [True]">
      <![CDATA[java.lang.AssertionError: expected [False] but found [True]
at com.tricentis.sampleapp.Test.LoginTest2.TestCase2(LoginTest2.java:42)
at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
at java.lang.Thread.run(Unknown Source)
... Removed 18 stack frames]]>
    </failure>
  </testcase> <!-- TestCase2 -->
</testsuite> <!-- Test -->
